name: event_app
description: A new Flutter project.

version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  get_it: ^3.1.0
  provider: ^4.0.2
  flutter_staggered_animations: ^0.1.2
  flutter_dash: ^0.0.1
  flutter_range_slider: ^1.4.0
  flutter_date_pickers: ^0.0.6
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  firebase_analytics: ^5.0.11
  firebase_storage: ^3.1.1
  mask_text_input_formatter: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/background/
    - assets/events/
    - assets/people/
    - assets/icon/


  fonts:
    - family: Geosans
      fonts:
        - asset: fonts/GeosansLight.ttf
        - asset: fonts/GeosansLight-Oblique.ttf
          style: italic
